export const BUBBLES = [
    {
        title: "Érdeklődés",
        type: "select",
        options: [
            "a társadalmi körülmények javítása érdekében végzett munka",
            "absztrakt és alkotó munka",
            "adminisztráció, igazgatás",
            "adminisztrációval és politikával foglalkozni",
            "alkotó",
            "biológiával foglalkozni",
            "dolgok megmunkálása, előállítása",
            "dolgokkal vagy számokkal végzett munka",
            "eladni, vásárolni",
            "elektromos készülékekkel dolgozni",
            "elemző",
            "eljárások módszeres alkalmazása",
            "előír, szervezett, meghatározott sorrendet követő munka",
            "emberek között dolgozni",
            "emberek tanulmányozás, ötletek átadása",
            "embereken segíteni",
            "építőiparban dolgozni",
            "fémekkel dolgozni",
            "fizikai teherbírás",
            "formákkal, vonalakkal végzett munka",
            "gépeket összeszerelni és javítani",
            "gépekkel végzett munka",
            "gépi berendezések működését figyelni",
            "ipari érdeklődés",
            "irányítás és szervezés, elismerés kivívása",
            "irányító",
            "irodában dolgozni",
            "irodalom és nyelvek",
            "kereskedelem, eladás",
            "kézi erővel, szerszámmal végzett munka",
            "közgazdaság",
            "közösségi",
            "laboratóriumban dolgozni",
            "matematikával foglalkozni",
            "megvalósító",
            "módszeres",
            "műszaki érdeklődés",
            "művészeti érdeklődés",
            "művészettel foglalkozni",
            "növényekkel vagy állatokkal foglalkozni",
            "sport",
            "szabadban végzett munka",
            "szabadidőt kellemesen eltölteni",
            "szociális",
            "szociális (társadalmi) tevékenységgel foglalkozni",
            "szociális, humanisztikus",
            "szolgáltatás",
            "tárgyias",
            "technikai feladatokat ellátni",
            "természeti érdeklődés",
            "természettudományokkal foglalkozni",
            "testi erőt igénylő tevékenységek",
            "tiszta környezetben dolgozni",
            "tudományos érdeklődés",
            "tudományos vagy műszaki munka",
            "újító",
            "üzleti kapcsolat emberekkel",
            "védelem, tekintély",
            "vezetés",
            "zenével foglalkozni"
        ]
    },
    {
        title: "Képességek",
        type: "select",
        options: [
            "általános tanulási képesség",
            "emlékezőképesség",
            "fizikai teherbírás",
            "formaészlelés",
            "írott szövegben hibák felfedezése",
            "kapcsolatteremtő képesség",
            "kéz-szem koordináció",
            "kézügyesség",
            "kézügyesség (mozgás képesség)",
            "matematikai-logikai képesség",
            "nyelvi kifejezőképesség",
            "ötletgazdagság",
            "számolási képesség",
            "térbeli gondolkodás képesség",
            "térbeli tájékozódási képességek",
            "térelképzelés",
            "ujjügyesség"
        ]
    },
    {
        title: "Értékek",
        type: "select",
        options: [
            "altruizmus",
            "anyagiak",
            "esztétikum",
            "felügyeleti viszonyok, hierarchia",
            "fizikai környezet",
            "függetlenség",
            "irányítás",
            "jó munkahelyi légkör",
            "kevés szabály van",
            "kreativitás",
            "másokon segíthetek",
            "munkateljesítmény",
            "munkával kapcsolatos biztonság",
            "önérvényesítés",
            "presztízs",
            "sok pénzt lehet keresni",
            "sokat gondolkodhatom, használhatom az eszem",
            "szellemi ösztönzés",
            "társas kapcsolatok",
            "változatosság",
            "vezethetek, irányíthatok"
        ]
    },
    {
        title: "Munkamód",
        type: "select",
        options: [
            "adminisztrációhoz és üzleti élethez kapcsolódó feladatokban részt venni",
            "állatokkal foglalkozni",
            "anyanyelvemet vagy idegen nyelveket felhasználni munkámban",
            "aprólékos megoldások",
            "azonos emberek között",
            "csoportban dolgozni, együtt dolgozni másokkal",
            "egyedül dolgozni",
            "emberek között lenni, segíteni nekik, tanácsolni, befolyásolni őket döntéseikben",
            "iskolába járás",
            "iskolába járás nélkül",
            "kemény anyaggal",
            "kevés fizikai erő",
            "kevés mozgást igényel",
            "kézügyességet felhasználni, úgy dolgozni, hogy látjuk a munka eredményét",
            "kísérletezni, elemezni, kutatni, valamit részletesen kidolgozni",
            "különböző feladatok szervezését, koordinálását vállalni",
            "lágy anyaggal",
            "másokkal dolgozni",
            "még többet tudni, továbbtanulni valamilyen irányba",
            "művészi feladatok",
            "nagyvonalú megoldások",
            "növények ápolása",
            "önállóan, alkotó módon dolgozni, valami szépet létrehozni",
            "sok mozgással járó feladatokat végezni, ahol nem kell sokat egy helyben ülni",
            "sok mozgást igényel",
            "szabadban",
            "szakmai feladatokat egyedül, önállóan, jól megoldani",
            "számokkal dolgozni, kalkulációt, felméréseket készíteni, folyamatokat elindítani",
            "számolni kell",
            "szavakkal dolgozni",
            "szívesebben fejjel",
            "szívesebben kézzel",
            "szobában",
            "technikai érzék",
            "technikai, műszaki jellegű feladatokat megoldani, tervezni, ellenőrizni, kivitelezni",
            "testi erő",
            "ugyanabban az épületben",
            "új helyszíneken",
            "új személyek között",
            "vezető szerepre vállalkozni és felelősséget vállalni"
        ]
    },
    {
        title: "Pályák és tapasztalatok",
        type: "free"
    },
    {
        title: "Erőforrások és lehetőségek",
        type: "free"
    },
    {
        title: "Egyéb fontos szempontok",
        type: "free"
    }
];
